### Get Ranking
GET http://localhost:3001/ranking

### Get one by name from Ranking
GET http://localhost:3001/ranking/Meltan



### Create a new item in the Ranking, we have to upsert
POST http://localhost:3001/ranking/addNew
Content-Type:application/json

[
{
    "rank":"3",
    "poke_name":"Poipole",
    "type":"['Poison']", 
    "wins":"10",
    "loses":"5",
    "points":"5"
},
{
    "rank":"4",
    "poke_name":"Marshadow",
    "type":"['Fighting', 'Ghost']", 
    "wins":"10",
    "loses":"5",
    "points":"5"
}
]

### Create a new item in the Ranking, we have to upsert
POST http://localhost:3001/ranking/addNew
Content-Type:application/json

[
{
    "rank":"1",
    "poke_name":"Meltan",
    "type":"['Melmetal']", 
    "wins":"15",
    "loses":"5",
    "points":"10"
},
{
    "rank":"2",
    "poke_name":"Meltan2",
    "type":"['Melmetal']", 
    "wins":"10",
    "loses":"5",
    "points":"5"
}
]

### Change Ranking based on this URL
PUT http://localhost:3001/ranking/win/Meltan
Content-Type:application/json

### Change Ranking based on this URL
PUT http://localhost:3001/ranking/lose/Meltan
Content-Type:application/json

### Get one by name from Ranking
GET http://localhost:3001/ranking/Meltan